[package]
name = "wasmrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "greet"
path = "src/lib.rs"
crate-type =["cdylib"]

[dependencies]